config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   # delete "/products/:id", to: "products#destroy"
   # patch "/products/:id", to: "products#update"
   # # esta peticion de tipo patch para realizar cambios parciales a un recurso existente
   # post "/products", to: "products#create"
   # get "/products/new", to: "products#new", as: :new_product
   # get "/products", to: "products#index"
   # get "/products/:id", to: "products#show", as: :product
   # get "/products/:id/edit", to: "products#edit", as: :edit_product
   # CON LA RESOURCES nosotros podemos realizar todas las acciones dce CRUD
   # de una sola vez
   resources :products, path: "/"

  # show mostrar un unico producto en conccreto
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :photo
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # POR CADA ACCION QUE VENGA SE VA A LLAMAR A ESTE METODO
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env["HTTP_ACCEPT_LANGUAGE"].scan(/^[a-z]{2}/).first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.with_attached_photo
  end

  def show
    product # esta solo sería mandar llamar al metodo product y así poder mostrar
    # el producto en pantalla, mandar llamar nuestra instancia de productos, etc...
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    # pp @product esto es para mostarr el contenido de una varaible en pantalla
    if @product.save
      redirect_to products_path, notice: t("products.create.success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end
  # proddutc find va a buscar el id

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t("products.update.updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy
    redirect_to products_path, notice: t("products.destroy.destroyed"), status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo)
  end

  def product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
    <%= link_to t('.edit'), edit_category_path(category)%>
  </p>
</div>


<!-- para el nombre de la categoria si queremos forzar un 
titulo o un texto como un prefacio o un placeholder usamos 
el strong tag -->

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= render partial: 'category', collection: @categories%>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cursito para aprender a programar chido en rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
    <%= yield  %>
  </body>
</html>

app/views/products/_form.html.erb
<%=form_with model: @product do | form |  %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
    <%= error %>
    </div>
    <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product' do %>
    
    <h2> <%= product.title%> </h2>
    
    <span> <%=product.price%>$ </span>

    <span> <%= image_tag product.photo, width: 200 if product.photo.attached? %> </span>
    <% end %>

app/views/products/edit.html.erb
<h2> <%= t('products.edit.title')%> </h2> 

<%= render 'form'%> 

app/views/products/index.html.erb
<h1> <%= t('products.index.title') %> </h1>

<%= render partial: 'product', collection: @products%>

app/views/products/new.html.erb
<h2> <%= t('products.new.title') %> </h2> 

<%=form_with model: @product do | form |  %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
    <%= error %>
    </div>
    <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit %>
<% end %>

app/views/products/show.html.erb
<%= image_tag @product.photo, wdth: 200, heigth: 200 if @product.photo.attached? %>

<h1 class="title"> <%= @product.title %> </h1>

<p class="description"> <%= @product.description %> </p>

<span class="price"> <%= @product.price %> $ </span>

<%= link_to 'Editar producto', edit_product_path(@product)%>

<%= link_to 'Eliminar producto', product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm')
  }%>

app/views/shared/_flash.html.erb
<%= notice%>

<%= alert%>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1> Cursito Página de ventas </h1>
<% end %> 
<%= link_to 'agregar nuevo producto', new_product_path %>